package com.ram.agent;
import android.app.*; import android.os.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.media.MediaPlayer; import android.view.*; import android.view.inputmethod.InputMethodManager; import android.widget.*; import org.json.JSONObject; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets;
public class MainActivity extends Activity {
 private final int BG=Color.rgb(7,11,18),PANEL=Color.rgb(17,24,34),GREEN=Color.rgb(38,210,123),MUTED=Color.rgb(145,157,174); private LinearLayout chat; private ScrollView scroll; private EditText input; private TextView state; private final AIService ai=new AIService(); private boolean waiting=false; private MediaPlayer player;
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);} private GradientDrawable box(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private TextView txt(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);build();ram("أنا RAM. أبحث عن مشاريع وصفقات مدفوعة وليست وظائف. بعد اختيارك للفرصة أتابع المشروع من التنفيذ حتى التسليم والمستحقات.");}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(16),dp(12),dp(16),dp(12));setContentView(root);
  LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView logo=txt("R",22,Color.WHITE);logo.setGravity(Gravity.CENTER);logo.setTypeface(null,1);logo.setBackground(box(GREEN,15));h.addView(logo,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout id=new LinearLayout(this);id.setOrientation(LinearLayout.VERTICAL);id.setPadding(dp(11),0,0,0);TextView n=txt("RAM",23,Color.WHITE);n.setTypeface(null,1);id.addView(n);state=txt("● متصل • شريك الأعمال",12,GREEN);id.addView(state);h.addView(id,new LinearLayout.LayoutParams(0,-2,1));root.addView(h);
  TextView flow=txt("فرصة ← اختيارك ← تنفيذ ← تسليم ← متابعة ← مستحق",13,MUTED);flow.setPadding(0,dp(12),0,dp(9));root.addView(flow);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tools=new LinearLayout(this);
  chip(tools,"فرص","ابحث على الإنترنت عن فرص مشاريع وطلبات خدمات وصفقات مدفوعة وليست وظائف أو توظيف: ترجمة وكتابة، تصميم مواقع وبرمجة، تصميم هندسي وAutoCAD و3D وديكور، شحن ولوجستيات وتنسيق شحنات، ربط بائع بمشتري وموردين ومشترين، وساطة تجارية وعقارية. أعطني روابط ومصادر حقيقية وميزانية إن وجدت.");
  chip(tools,"إنجاز","ابدأ تنفيذ المشروع الذي اخترته: افهم المطلوب، حدد المخرجات، أنجز العمل القابل للتنفيذ، جهز التسليم، ثم تابع المستحقات. لا تدّع إجراء خارجياً لم تنفذه أداة متصلة.");
  chip(tools,"متابعة","تابع المشروع المختار من آخر حالة: الاتفاق، التنفيذ، المراجعة، التسليم، انتظار الرد، ثم المستحق.");
  chip(tools,"شحن","ابحث عن طلبات شحن وتنسيق لوجستي حقيقية بحرياً وجوياً وبرياً وأصحاب بضائع يحتاجون ناقلاً أو وسيطاً. لا تعرض وظائف.");
  chip(tools,"مستحقات","تابع مستحقات المشاريع المسلمة. لا تعتبر أي مبلغ مستلماً حتى أؤكد أنا وصوله.");hs.addView(tools);root.addView(hs);
  scroll=new ScrollView(this);scroll.setFillViewport(true);chat=new LinearLayout(this);chat.setOrientation(LinearLayout.VERTICAL);scroll.addView(chat);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(5),dp(5),dp(5),dp(5));c.setBackground(box(Color.rgb(22,31,43),21));input=new EditText(this);input.setHint("اكتب إلى RAM…");input.setHintTextColor(MUTED);input.setTextColor(Color.WHITE);input.setTextSize(16);input.setMaxLines(5);input.setBackgroundColor(Color.TRANSPARENT);c.addView(input,new LinearLayout.LayoutParams(0,-2,1));TextView send=txt("➤",24,Color.WHITE);send.setGravity(Gravity.CENTER);send.setBackground(box(GREEN,18));send.setOnClickListener(v->send());c.addView(send,new LinearLayout.LayoutParams(dp(50),dp(50)));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(4),0,dp(30));root.addView(c,cp);}
 private void chip(LinearLayout p,String t,String q){TextView v=txt(t,13,Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(dp(15),0,dp(15),0);v.setBackground(box(Color.rgb(22,31,43),18));LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-2,dp(42));x.setMargins(0,0,dp(8),0);p.addView(v,x);v.setOnClickListener(z->{input.setText(q);input.setSelection(input.length());});}
 private void send(){String m=input.getText().toString().trim();if(m.isEmpty()||waiting)return;input.setText("");user(m);waiting=true;state.setText("● RAM يعمل…");((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);ai.askAI(m,new AIService.AIResponseCallback(){public void onSuccess(String r){waiting=false;state.setText("● متصل • شريك الأعمال");ram(r);playVoice(r);}public void onError(String e){waiting=false;state.setText("● تعذر الاتصال");ram("تعذر الوصول إلى خادم RAM.\n"+e);}});}
 private void user(String s){bubble("أنت",s,Color.rgb(27,94,68),Gravity.RIGHT);} private void ram(String s){bubble("RAM",s,PANEL,Gravity.LEFT);} private void bubble(String w,String s,int c,int g){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(14),dp(10),dp(14),dp(12));b.setBackground(box(c,17));b.addView(txt(w,11,w.equals("RAM")?GREEN:Color.WHITE));TextView m=txt(s,16,Color.WHITE);m.setTextIsSelectable(true);b.addView(m);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.gravity=g;p.setMargins(dp(3),dp(5),dp(3),dp(5));chat.addView(b,p);scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}
 private void playVoice(String text){final String spoken=text.replace("**","").replace("#","").replace("`","");new Thread(()->{HttpURLConnection c=null;File f=null;try{c=(HttpURLConnection)new URL(AIService.SERVER+"/tts").openConnection();c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json; charset=UTF-8");c.setDoOutput(true);JSONObject j=new JSONObject();j.put("text",spoken.length()>1200?spoken.substring(0,1200):spoken);try(OutputStream o=c.getOutputStream()){o.write(j.toString().getBytes(StandardCharsets.UTF_8));}if(c.getResponseCode()<200||c.getResponseCode()>=300)return;f=File.createTempFile("ram_",".mp3",getCacheDir());try(InputStream in=c.getInputStream();FileOutputStream out=new FileOutputStream(f)){byte[]b=new byte[8192];int k;while((k=in.read(b))>0)out.write(b,0,k);}File a=f;runOnUiThread(()->{try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(a.getAbsolutePath());player.setOnCompletionListener(mp->{mp.release();player=null;a.delete();});player.prepare();player.start();}catch(Exception e){a.delete();}});}catch(Exception e){if(f!=null)f.delete();}finally{if(c!=null)c.disconnect();}}).start();}
 protected void onDestroy(){if(player!=null)player.release();super.onDestroy();}
}