package com.ram.agent;

import android.app.*;import android.app.job.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.media.MediaPlayer;import android.speech.RecognizerIntent;import android.speech.tts.TextToSpeech;import android.speech.tts.Voice;import android.webkit.*;import android.widget.Toast;import android.view.*;import org.json.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

/** Local packaged UI only. No remote page is allowed access to the bridge. */
public class MainActivity extends Activity {
 private WebView web;private SharedPreferences prefs;private TextToSpeech speech;private MediaPlayer cloudPlayer;private boolean ready,dead;private volatile HttpURLConnection request,ttsRequest;private boolean busy;
 private static final int VOICE=31,EXPORT=32,NOTIFICATIONS=33;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("ram_business",MODE_PRIVATE);getWindow().setStatusBarColor(Color.rgb(8,13,24));getWindow().setNavigationBarColor(Color.rgb(8,13,24));getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
  android.widget.FrameLayout root=new android.widget.FrameLayout(this);web=new WebView(this);root.addView(web);setContentView(root);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});root.requestApplyInsets();
  WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(false);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setAllowFileAccessFromFileURLs(false);settings.setAllowUniversalAccessFromFileURLs(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.setBackgroundColor(Color.rgb(8,13,24));
  web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(!u.startsWith("file:///android_asset/"))return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));return null;}});
  web.addJavascriptInterface(new Bridge(),"Android");web.loadUrl("file:///android_asset/index.html");speech=new TextToSpeech(this,status->{if(!dead&&speech!=null&&status==TextToSpeech.SUCCESS){int lang=speech.setLanguage(new Locale("ar"));ready=lang>=0;}});
 }
 private void js(String fn,String value){runOnUiThread(()->{if(!dead)web.evaluateJavascript("window."+fn+"("+value+")",null);});}
 private void message(String value){runOnUiThread(()->Toast.makeText(this,value,Toast.LENGTH_LONG).show());}
 private class Bridge {
  @JavascriptInterface public String load(){return prefs.getString("state","null");}
  @JavascriptInterface public boolean save(String data){try{if(data.length()>5000000)return false;JSONObject j=new JSONObject(data);if(j.optInt("version")!=1||j.optJSONArray("jobs")==null||j.optJSONArray("contacts")==null)return false;return prefs.edit().putString("state",data).commit();}catch(Exception e){return false;}}
  @JavascriptInterface public boolean setConnectionToken(String token){if(token.length()<24||token.length()>512)return false;return prefs.edit().putString("connection_token",token).commit();}
  @JavascriptInterface public String getVoices(){JSONArray a=new JSONArray();if(speech!=null&&speech.getVoices()!=null)for(Voice v:speech.getVoices())if("ar".equals(v.getLocale().getLanguage())){JSONObject item=new JSONObject();try{item.put("name",v.getName());item.put("locale",v.getLocale().toLanguageTag());a.put(item);}catch(Exception ignored){}}return a.toString();}
  @JavascriptInterface public boolean setVoice(String name){return name==null||name.isEmpty()?true:selectVoice(name);}
  @JavascriptInterface public boolean setVoicePitch(String pitch){if(!Arrays.asList("low","normal","high").contains(pitch))return false;prefs.edit().putString("voice_pitch",pitch).commit();return true;}
  @JavascriptInterface public void checkCapabilities(){requestStatus("capabilities");}
  @JavascriptInterface public void search(String query){requestStatus("search",query);}
  @JavascriptInterface public String newId(){return UUID.randomUUID().toString();}
  private boolean selectVoice(String name){if(speech==null)return false;if(name==null||name.isEmpty()){ready=speech.setLanguage(new Locale("ar"))>=0;if(ready)prefs.edit().remove("tts_voice").commit();return ready;}if(speech.getVoices()==null)return false;for(Voice v:speech.getVoices())if(v.getName().equals(name)&&"ar".equals(v.getLocale().getLanguage())){speech.setVoice(v);prefs.edit().putString("tts_voice",name).commit();ready=true;return true;}return false;}
  private void requestStatus(String endpoint){requestStatus(endpoint,null);}
  private void requestStatus(String endpoint,String query){new Thread(()->{JSONObject payload=new JSONObject();try{if(query!=null)payload.put("query",query);String value=post(endpoint,payload);JSONObject answer=new JSONObject(value);if(query!=null)js("searchReply",answer.toString());else js("capabilitiesReply",answer.toString());}catch(Exception ex){JSONObject err=new JSONObject();try{err.put("error","تعذر التحقق من الاتصال؛ راجع رمز الخادم والشبكة");}catch(Exception ignored){}String out=err.toString();js(query==null?"capabilitiesReply":"searchReply",out);}} ,"ram-"+endpoint).start();}
  @JavascriptInterface public void setServer(String u){try{URL v=new URL(u);if(v.getProtocol().equals("https")&&v.getUserInfo()==null&&v.getQuery()==null&&v.getRef()==null)prefs.edit().putString("server",u.replaceAll("/+$","")).apply();}catch(Exception e){message("رابط الخادم غير صالح");}}
  @JavascriptInterface public void openUrl(String u){runOnUiThread(()->{try{Uri uri=Uri.parse(u);if(!"https".equals(uri.getScheme())&&!"http".equals(uri.getScheme()))return;startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){message("تعذر فتح الرابط");}});}
  @JavascriptInterface public void chat(String data){runOnUiThread(()->send(data));}
  @JavascriptInterface public void speak(String text){runOnUiThread(()->{stopCloudPlayback();if(ready){String selected=prefs.getString("tts_voice","");if(!selected.isEmpty())selectVoice(selected);float rate="low".equals(prefs.getString("voice_pitch","normal"))?.9f:"high".equals(prefs.getString("voice_pitch","normal"))?1.1f:1f;speech.setSpeechRate(rate);speech.speak(text.substring(0,Math.min(text.length(),TextToSpeech.getMaxSpeechInputLength())),TextToSpeech.QUEUE_FLUSH,null,"ram");}else message("ثبّت صوتًا عربيًا في إعدادات تحويل النص إلى كلام");});}
  @JavascriptInterface public void speakCloud(String text){if(text==null||text.trim().isEmpty())return;String value=text.trim().substring(0,Math.min(text.trim().length(),1200));new Thread(()->{File audio=null;try{if(speech!=null)speech.stop();JSONObject body=new JSONObject();body.put("text",value);byte[] bytes=postAudio("tts",body);audio=File.createTempFile("ram-voice-",".mp3",getCacheDir());try(FileOutputStream out=new FileOutputStream(audio)){out.write(bytes);}File readyFile=audio;runOnUiThread(()->playCloudAudio(readyFile));}catch(Exception e){if(audio!=null)audio.delete();String why=e.getMessage()==null?"تعذر طلب صوت ElevenLabs":e.getMessage();message(why);}} ,"ram-elevenlabs").start();}
  @JavascriptInterface public void stopVoice(){runOnUiThread(()->{if(speech!=null)speech.stop();stopCloudPlayback();HttpURLConnection c=ttsRequest;if(c!=null)c.disconnect();});}
  @JavascriptInterface public void dictate(){runOnUiThread(()->{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ar-YE");try{startActivityForResult(i,VOICE);}catch(Exception e){message("خدمة التعرف على الكلام غير متاحة");}});}
  @JavascriptInterface public void exportData(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"RAM-business-backup.json");try{startActivityForResult(i,EXPORT);}catch(Exception e){message("تعذر فتح اختيار مكان الحفظ");}});}
  @JavascriptInterface public void enableReminders(){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},NOTIFICATIONS);else schedule();});}
 }
 private String post(String endpoint,JSONObject body)throws Exception{HttpURLConnection c=null;try{String server=prefs.getString("server","https://ram-agent-production.up.railway.app");c=(HttpURLConnection)new URL(server+"/"+endpoint).openConnection();request=c;c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json; charset=UTF-8");String token=prefs.getString("connection_token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream stream=code>=200&&code<300?c.getInputStream():c.getErrorStream();String raw=read(stream);if(code<200||code>=300)throw new IOException(code==401?"رمز الاتصال مرفوض":code==429?"طلبات كثيرة؛ حاول لاحقًا":"الخادم لم يقبل الطلب");return raw;}finally{if(c!=null)c.disconnect();request=null;}}
 private byte[] postAudio(String endpoint,JSONObject body)throws Exception{HttpURLConnection c=null;try{String server=prefs.getString("server","https://ram-agent-production.up.railway.app");c=(HttpURLConnection)new URL(server+"/"+endpoint).openConnection();ttsRequest=c;c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json; charset=UTF-8");String token=prefs.getString("connection_token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();if(code<200||code>=300){String error=read(c.getErrorStream());if(code==401)throw new IOException("رمز الاتصال مرفوض؛ راجع رمز RAM_API_TOKEN في إعدادات رام");if(code==503&&error.contains("معطّل"))throw new IOException("ElevenLabs محفوظ لكنه غير مفعّل في الخادم بعد");if(code==429)throw new IOException("طلبات كثيرة؛ حاول لاحقًا");throw new IOException("تعذر توليد صوت ElevenLabs؛ راجع إعداد الخدمة");}if(c.getContentLength()>4_000_000)throw new IOException("ملف الصوت أكبر من الحد المسموح");try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(out.size()+n>4_000_000)throw new IOException("ملف الصوت أكبر من الحد المسموح");out.write(buf,0,n);}return out.toByteArray();}}finally{if(c!=null)c.disconnect();ttsRequest=null;}}
 private void playCloudAudio(File file){if(dead){file.delete();return;}stopCloudPlayback();try{MediaPlayer player=new MediaPlayer();cloudPlayer=player;player.setDataSource(file.getAbsolutePath());player.setOnCompletionListener(p->{p.release();if(cloudPlayer==p)cloudPlayer=null;file.delete();});player.setOnErrorListener((p,what,extra)->{p.release();if(cloudPlayer==p)cloudPlayer=null;file.delete();message("تعذر تشغيل ملف صوت ElevenLabs");return true;});player.setOnPreparedListener(MediaPlayer::start);player.prepareAsync();}catch(Exception e){stopCloudPlayback();file.delete();message("تعذر تشغيل صوت ElevenLabs");}}
 private void stopCloudPlayback(){MediaPlayer p=cloudPlayer;cloudPlayer=null;if(p!=null){try{p.stop();}catch(Exception ignored){}try{p.release();}catch(Exception ignored){}}}
 private void send(String data){if(busy||dead)return;busy=true;new Thread(()->{JSONObject result=new JSONObject();try{
  JSONObject body=new JSONObject(data);JSONObject answer=new JSONObject(post("chat",body));
  result=answer;
 }catch(Exception e){try{result.put("error",e.getMessage()!=null&&e.getMessage().length()<120?e.getMessage():"تعذر إكمال الاتصال؛ تحقق من الشبكة أو إعداد الخادم");}catch(Exception ignored){}}String output=result.toString();runOnUiThread(()->{busy=false;js("reply",output);});},"ram-chat").start();}
 private String read(InputStream in)throws Exception{if(in==null)return "{}";try(Reader r=new InputStreamReader(in,StandardCharsets.UTF_8)){StringBuilder b=new StringBuilder();char[] buf=new char[4096];int n;while((n=r.read(buf))!=-1){if(b.length()+n>1000000)throw new IOException();b.append(buf,0,n);}return b.toString();}}
 private void schedule(){JobScheduler j=(JobScheduler)getSystemService(JOB_SCHEDULER_SERVICE);int ok=j.schedule(new JobInfo.Builder(71717,new ComponentName(this,ReminderService.class)).setPeriodic(3600000).setPersisted(true).build());message(ok==JobScheduler.RESULT_SUCCESS?"تم تفعيل تذكير محلي تقريبي؛ لا يعمل والهاتف مطفأ":"تعذر جدولة التنبيه");}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==NOTIFICATIONS&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)schedule();}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==VOICE){ArrayList<String> words=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(words!=null&&!words.isEmpty())js("voiceText",JSONObject.quote(words.get(0)));}if(r==EXPORT&&d.getData()!=null){try(OutputStream out=getContentResolver().openOutputStream(d.getData())){if(out==null)throw new IOException();out.write(prefs.getString("state","{}").getBytes(StandardCharsets.UTF_8));message("حُفظت النسخة الاحتياطية في المكان الذي اخترته");}catch(Exception e){message("تعذر حفظ النسخة الاحتياطية");}}}
 @Override protected void onDestroy(){dead=true;if(request!=null)request.disconnect();if(ttsRequest!=null)ttsRequest.disconnect();stopCloudPlayback();if(speech!=null){speech.stop();speech.shutdown();}web.removeJavascriptInterface("Android");web.destroy();super.onDestroy();}
}
