package com.ram.agent;

import android.app.*;import android.app.job.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.media.MediaPlayer;import android.speech.tts.TextToSpeech;import android.speech.tts.Voice;import android.webkit.*;import android.widget.Toast;import android.view.*;import org.json.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

/** Local packaged UI only. No remote page is allowed access to the bridge. */
public class MainActivity extends Activity {
 private WebView web;private SharedPreferences prefs;private TextToSpeech speech;private MediaPlayer cloudPlayer;private boolean ready,dead;private volatile HttpURLConnection request,ttsRequest;private boolean busy;private boolean voiceReceiverRegistered;private BroadcastReceiver voiceReceiver;
 private static final int EXPORT=32,NOTIFICATIONS=33,PROFILE=34,VOICE_PERMISSION=35,JOB_EXPORT=36;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("ram_business",MODE_PRIVATE);getWindow().setStatusBarColor(Color.rgb(8,13,24));getWindow().setNavigationBarColor(Color.rgb(8,13,24));getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
  android.widget.FrameLayout root=new android.widget.FrameLayout(this);web=new WebView(this);root.addView(web);setContentView(root);root.setOnApplyWindowInsetsListener((v,i)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=i.getInsets(WindowInsets.Type.systemBars()),ime=i.getInsets(WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,ime.bottom));}else v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});root.requestApplyInsets();
  WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(false);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setAllowFileAccessFromFileURLs(false);settings.setAllowUniversalAccessFromFileURLs(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.setBackgroundColor(Color.rgb(8,13,24));
  web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(!u.startsWith("file:///android_asset/"))return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));return null;}@Override public void onPageFinished(WebView v,String u){if(u.startsWith("file:///android_asset/"))js("voiceSessionChanged",voiceSessionActive()?"true":"false");}});
  web.addJavascriptInterface(new Bridge(),"Android");web.loadUrl("file:///android_asset/index.html");registerVoiceReceiver();speech=new TextToSpeech(this,status->{if(!dead&&speech!=null&&status==TextToSpeech.SUCCESS){int lang=speech.setLanguage(new Locale("ar"));ready=lang>=0;}});
 }
 private void js(String fn,String value){runOnUiThread(()->{if(!dead)web.evaluateJavascript("window."+fn+"("+value+")",null);});}
 private void message(String value){runOnUiThread(()->Toast.makeText(this,value,Toast.LENGTH_LONG).show());}
 private class Bridge {
  @JavascriptInterface public String load(){return prefs.getString("state","null");}
  @JavascriptInterface public boolean save(String data){try{if(data.length()>5000000)return false;JSONObject j=new JSONObject(data);if(j.optInt("version")!=1||j.optJSONArray("jobs")==null||j.optJSONArray("contacts")==null)return false;return prefs.edit().putString("state",data).commit();}catch(Exception e){return false;}}
  @JavascriptInterface public boolean setConnectionToken(String token){if(token.length()<24||token.length()>512)return false;return prefs.edit().putString("connection_token",token).commit();}
  @JavascriptInterface public String getVoices(){JSONArray a=new JSONArray();if(speech!=null&&speech.getVoices()!=null)for(Voice v:speech.getVoices())if("ar".equals(v.getLocale().getLanguage())){JSONObject item=new JSONObject();try{item.put("name",v.getName());item.put("locale",v.getLocale().toLanguageTag());a.put(item);}catch(Exception ignored){}}return a.toString();}
  @JavascriptInterface public boolean setVoice(String name){return name==null||name.isEmpty()?true:selectVoice(name);}
  @JavascriptInterface public boolean setVoicePitch(String pitch){if(!Arrays.asList("low","normal","high").contains(pitch))return false;prefs.edit().putString("voice_pitch",pitch).commit();return true;}
  @JavascriptInterface public void checkCapabilities(){requestStatus("capabilities");}
  @JavascriptInterface public void showKeyboard(){runOnUiThread(()->{if(dead||web==null)return;web.requestFocus();web.postDelayed(()->{if(dead)return;android.view.inputmethod.InputMethodManager imm=(android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);if(imm!=null)imm.showSoftInput(web,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);},80);});}
  @JavascriptInterface public void search(String query){requestStatus("search",query);}
  @JavascriptInterface public void gmailStart(){new Thread(()->{try{JSONObject data=new JSONObject(get("gmail/oauth/start"));String value=data.optString("authorizationUrl","");URL url=new URL(value);if(!"https".equals(url.getProtocol())||!"accounts.google.com".equals(url.getHost()))throw new IOException("رابط تفويض Google غير صالح");runOnUiThread(()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(value)));JSONObject ok=new JSONObject();try{ok.put("ok",true);}catch(Exception ignored){}js("gmailStartReply",ok.toString());}catch(Exception e){js("gmailStartReply",errorJson(new IOException("تعذر فتح صفحة Google")).toString());}});}catch(Exception e){js("gmailStartReply",errorJson(e).toString());}} ,"ram-gmail-oauth").start();}
  @JavascriptInterface public void gmailStatus(){requestGmail("gmail/status",new JSONObject(),"gmailStatusReply");}
  @JavascriptInterface public void gmailInbox(){requestGmail("gmail/inbox",new JSONObject(),"gmailInboxReply");}
  @JavascriptInterface public void n8nTest(){JSONObject body=new JSONObject();try{body.put("confirmed",true);}catch(Exception ignored){}requestGmail("integrations/n8n/test",body,"n8nTestReply");}
  @JavascriptInterface public void n8nRun(String data){try{JSONObject body=new JSONObject(data);body.put("confirmed",true);requestGmail("integrations/n8n/execute",body,"n8nRunReply");}catch(Exception e){js("n8nRunReply",errorJson(e).toString());}}
  @JavascriptInterface public void gmailSend(String data){try{JSONObject body=new JSONObject(data);body.put("confirmed",true);requestGmail("gmail/send",body,"gmailSendReply");}catch(Exception e){js("gmailSendReply",errorJson(e).toString());}}
  @JavascriptInterface public String newId(){return UUID.randomUUID().toString();}
  private boolean selectVoice(String name){if(speech==null)return false;if(name==null||name.isEmpty()){ready=speech.setLanguage(new Locale("ar"))>=0;if(ready)prefs.edit().remove("tts_voice").commit();return ready;}if(speech.getVoices()==null)return false;for(Voice v:speech.getVoices())if(v.getName().equals(name)&&"ar".equals(v.getLocale().getLanguage())){speech.setVoice(v);prefs.edit().putString("tts_voice",name).commit();ready=true;return true;}return false;}
  private void requestStatus(String endpoint){requestStatus(endpoint,null);}
  private void requestStatus(String endpoint,String query){new Thread(()->{JSONObject payload=new JSONObject();try{if(query!=null)payload.put("query",query);String value=post(endpoint,payload);JSONObject answer=new JSONObject(value);if(query!=null)js("searchReply",answer.toString());else js("capabilitiesReply",answer.toString());}catch(Exception ex){JSONObject err=new JSONObject();try{String reason=ex.getMessage();err.put("error",reason==null||reason.isEmpty()?"تعذر الاتصال بالخادم؛ تحقق من الشبكة وإعداد الرابط":reason);}catch(Exception ignored){}String out=err.toString();js(query==null?"capabilitiesReply":"searchReply",out);}} ,"ram-"+endpoint).start();}
  @JavascriptInterface public void setServer(String u){try{URL v=new URL(u);if(v.getProtocol().equals("https")&&v.getUserInfo()==null&&v.getQuery()==null&&v.getRef()==null)prefs.edit().putString("server",u.replaceAll("/+$","")).apply();}catch(Exception e){message("رابط الخادم غير صالح");}}
  @JavascriptInterface public void openUrl(String u){runOnUiThread(()->{try{Uri uri=Uri.parse(u);if(!"https".equals(uri.getScheme())&&!"http".equals(uri.getScheme()))return;startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){message("تعذر فتح الرابط");}});}
  @JavascriptInterface public void chat(String data){runOnUiThread(()->send(data));}
  @JavascriptInterface public void speak(String text){runOnUiThread(()->{stopCloudPlayback();if(ready){String selected=prefs.getString("tts_voice","");if(!selected.isEmpty())selectVoice(selected);float rate="low".equals(prefs.getString("voice_pitch","normal"))?.9f:"high".equals(prefs.getString("voice_pitch","normal"))?1.1f:1f;speech.setSpeechRate(rate);if(Build.VERSION.SDK_INT>=21){speech.setOnUtteranceProgressListener(new android.speech.tts.UtteranceProgressListener(){@Override public void onStart(String id){}@Override public void onDone(String id){if("ram-voice-session".equals(id))resumeVoiceRecognition();}@Override public void onError(String id){if("ram-voice-session".equals(id))resumeVoiceRecognition();}});}speech.speak(text.substring(0,Math.min(text.length(),TextToSpeech.getMaxSpeechInputLength())),TextToSpeech.QUEUE_FLUSH,null,voiceSessionActive()?"ram-voice-session":"ram");}else{message("ثبّت صوتًا عربيًا في إعدادات تحويل النص إلى كلام");resumeVoiceRecognition();}});}
  @JavascriptInterface public void speakCloud(String text){if(text==null||text.trim().isEmpty())return;String value=text.trim().substring(0,Math.min(text.trim().length(),1200));new Thread(()->{File audio=null;try{if(speech!=null)speech.stop();JSONObject body=new JSONObject();body.put("text",value);byte[] bytes=postAudio("tts",body);audio=File.createTempFile("ram-voice-",".mp3",getCacheDir());try(FileOutputStream out=new FileOutputStream(audio)){out.write(bytes);}File readyFile=audio;runOnUiThread(()->playCloudAudio(readyFile));}catch(Exception e){if(audio!=null)audio.delete();String why=e.getMessage()==null?"تعذر طلب صوت ElevenLabs":e.getMessage();message(why);resumeVoiceRecognition();}} ,"ram-elevenlabs").start();}
  @JavascriptInterface public void stopVoice(){runOnUiThread(()->{if(speech!=null)speech.stop();stopCloudPlayback();HttpURLConnection c=ttsRequest;if(c!=null)c.disconnect();});}
  @JavascriptInterface public void startVoiceSession(){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},VOICE_PERMISSION);return;}startVoiceService();});}
  @JavascriptInterface public void stopVoiceSession(){runOnUiThread(()->{Intent i=new Intent(MainActivity.this,VoiceConversationService.class);i.setAction(VoiceConversationService.ACTION_STOP);startService(i);if(speech!=null)speech.stop();stopCloudPlayback();js("voiceSessionChanged","false");});}
  @JavascriptInterface public void pauseVoiceSession(){try{Intent i=new Intent(MainActivity.this,VoiceConversationService.class);i.setAction(VoiceConversationService.ACTION_PAUSE);startService(i);}catch(Exception ignored){}}
  @JavascriptInterface public void resumeVoiceSession(){resumeVoiceRecognition();}
  @JavascriptInterface public void exportJobFile(String name,String content){String file=String.valueOf(name==null?"":name).replaceAll("[\\\\/:*?\"<>|]","_").trim();String data=String.valueOf(content==null?"":content);if(file.isEmpty()||data.isEmpty()||data.length()>100000){message("اسم الملف أو محتواه غير صالح أو أكبر من الحد");return;}runOnUiThread(()->{prefs.edit().putString("job_export_name",file).putString("job_export_content",data).apply();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/markdown");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,file);try{startActivityForResult(i,JOB_EXPORT);}catch(Exception e){prefs.edit().remove("job_export_name").remove("job_export_content").apply();message("تعذر فتح اختيار مكان حفظ المخرج");}});}   @JavascriptInterface public void exportData(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"RAM-business-backup.json");try{startActivityForResult(i,EXPORT);}catch(Exception e){message("تعذر فتح اختيار مكان الحفظ");}});}
  @JavascriptInterface public void exportProfile(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/pdf");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"Enjaz_Holding_Company_Profile_AR.pdf");try{startActivityForResult(i,PROFILE);}catch(Exception e){message("تعذر فتح اختيار مكان حفظ ملف الخبرة");}});}
  @JavascriptInterface public void shareProfile(){runOnUiThread(()->{String text="إنجاز القابضة\nشركة خدمات وتنسيق أعمال متعددة المجالات. تاريخ بدء العمل المذكور من المالك: 2020.\n\nالخدمات: الهندسة ومخططات المساحة والديكور والتصميم؛ تصميم المواقع والبرمجة؛ الأبحاث والاستشارات ودراسات المشاريع؛ الترجمة؛ تنسيق الشحن الجوي والبحري والبري؛ الوساطة في التوريد؛ وتنسيق الاستفسارات التجارية في النفط والغاز وفق الأنظمة.\n\nالتواصل: أحمد عبدالكريم أحمد عشيش\nالهاتف: +967 713 377 288\n\nملاحظة: تاريخ العمل والخدمات معلومات قدمها مالك الشركة. لا يتضمن الملف الحالي شهادات تسجيل أو مراجع عملاء أو نماذج أعمال موثقة.";Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_SUBJECT,"الملف التعريفي لشركة إنجاز القابضة");send.putExtra(Intent.EXTRA_TEXT,text);try{startActivity(Intent.createChooser(send,"مشاركة نبذة الشركة"));}catch(Exception e){message("لا يوجد تطبيق متاح للمشاركة");}});}
  @JavascriptInterface public void enableReminders(){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},NOTIFICATIONS);else schedule();});}
  private void requestGmail(String endpoint,JSONObject body,String callback){new Thread(()->{try{js(callback,new JSONObject(post(endpoint,body)).toString());}catch(Exception e){js(callback,errorJson(e).toString());}},"ram-"+endpoint.replace('/','-')).start();}
  private JSONObject errorJson(Exception e){JSONObject out=new JSONObject();try{String reason=e.getMessage();out.put("error",reason==null||reason.isEmpty()?"تعذر الاتصال بالخادم؛ تحقق من الإعدادات والشبكة":reason);}catch(Exception ignored){}return out;}
 }
 private String serverBaseUrl(){String current=prefs.getString("server","https://ram-agent-production-33c2.up.railway.app");try{URL parsed=new URL(current);if("ram-agent-production.up.railway.app".equalsIgnoreCase(parsed.getHost())){current="https://ram-agent-production-33c2.up.railway.app";prefs.edit().putString("server",current).apply();}}catch(Exception ignored){current="https://ram-agent-production-33c2.up.railway.app";prefs.edit().putString("server",current).apply();}return current.replaceAll("/+$","");}
  private String get(String endpoint)throws Exception{HttpURLConnection c=null;try{String server=serverBaseUrl();c=(HttpURLConnection)new URL(server+"/"+endpoint).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestMethod("GET");String token=prefs.getString("connection_token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);int code=c.getResponseCode();String raw=read(code>=200&&code<300?c.getInputStream():c.getErrorStream());if(code<200||code>=300){try{String reason=new JSONObject(raw).optString("error","");if(!reason.isEmpty())throw new IOException(reason);}catch(org.json.JSONException ignored){}throw new IOException("تعذر بدء ربط Gmail ("+code+")");}return raw;}finally{if(c!=null)c.disconnect();}}
 private String post(String endpoint,JSONObject body)throws Exception{HttpURLConnection c=null;try{String server=serverBaseUrl();c=(HttpURLConnection)new URL(server+"/"+endpoint).openConnection();request=c;c.setInstanceFollowRedirects(false);c.setUseCaches(false);c.setConnectTimeout(20000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setRequestProperty("Connection","close");c.setRequestProperty("Content-Type","application/json; charset=UTF-8");String token=prefs.getString("connection_token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream stream=code>=200&&code<300?c.getInputStream():c.getErrorStream();String raw=read(stream);if(code<200||code>=300){String reason=code==401?"رمز الاتصال مرفوض؛ راجعه في إعدادات رام":code==429?"طلبات كثيرة؛ حاول لاحقًا":"الخادم رفض الطلب ("+code+")";try{String reported=new JSONObject(raw).optString("error","");if(!reported.isEmpty()&&reported.length()<=240)reason=reported;}catch(Exception ignored){}throw new IOException(reason);}return raw;}finally{if(c!=null)c.disconnect();request=null;}}
 private byte[] postAudio(String endpoint,JSONObject body)throws Exception{HttpURLConnection c=null;try{String server=serverBaseUrl();c=(HttpURLConnection)new URL(server+"/"+endpoint).openConnection();ttsRequest=c;c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json; charset=UTF-8");String token=prefs.getString("connection_token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();if(code<200||code>=300){String error=read(c.getErrorStream());if(code==401)throw new IOException("رمز الاتصال مرفوض؛ راجع رمز RAM_API_TOKEN في إعدادات رام");if(code==503&&error.contains("معطّل"))throw new IOException("ElevenLabs محفوظ لكنه غير مفعّل في الخادم بعد");if(code==429)throw new IOException("طلبات كثيرة؛ حاول لاحقًا");throw new IOException("تعذر توليد صوت ElevenLabs؛ راجع إعداد الخدمة");}if(c.getContentLength()>4_000_000)throw new IOException("ملف الصوت أكبر من الحد المسموح");try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(out.size()+n>4_000_000)throw new IOException("ملف الصوت أكبر من الحد المسموح");out.write(buf,0,n);}return out.toByteArray();}}finally{if(c!=null)c.disconnect();ttsRequest=null;}}
 private void playCloudAudio(File file){if(dead){file.delete();return;}stopCloudPlayback();try{MediaPlayer player=new MediaPlayer();cloudPlayer=player;player.setDataSource(file.getAbsolutePath());player.setOnCompletionListener(p->{p.release();if(cloudPlayer==p)cloudPlayer=null;file.delete();resumeVoiceRecognition();});player.setOnErrorListener((p,what,extra)->{p.release();if(cloudPlayer==p)cloudPlayer=null;file.delete();message("تعذر تشغيل ملف صوت ElevenLabs");resumeVoiceRecognition();return true;});player.setOnPreparedListener(MediaPlayer::start);player.prepareAsync();}catch(Exception e){stopCloudPlayback();file.delete();message("تعذر تشغيل صوت ElevenLabs");resumeVoiceRecognition();}}
 private void stopCloudPlayback(){MediaPlayer p=cloudPlayer;cloudPlayer=null;if(p!=null){try{p.stop();}catch(Exception ignored){}try{p.release();}catch(Exception ignored){}}}
 private void send(String data){if(busy||dead)return;busy=true;new Thread(()->{JSONObject result=new JSONObject();try{
  JSONObject body=new JSONObject(data);JSONObject answer=new JSONObject(postChat(body));
  result=answer;
 }catch(Exception e){try{String reason=e.getMessage()==null?"":e.getMessage();if(reason.matches("(?is).*(connection abort|connection reset|software caused|broken pipe|timed? ?out|econnreset).*"))reason="انقطع الاتصال بالخادم قبل اكتمال الرد. أعد المحاولة؛ لم يُسجّل إنجاز للعمل.";result.put("error",reason.length()>0&&reason.length()<180?reason:"تعذر إكمال الاتصال؛ تحقق من الشبكة أو إعداد الخادم");}catch(Exception ignored){}}String output=result.toString();runOnUiThread(()->{busy=false;js("reply",output);});},"ram-chat").start();}
 private String postChat(JSONObject body)throws Exception{try{return post("chat",body);}catch(IOException first){String reason=first.getMessage()==null?"":first.getMessage();if(!reason.matches("(?is).*(connection abort|connection reset|software caused|broken pipe|timed? ?out|econnreset).*"))throw first;try{Thread.sleep(800);}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw first;}return post("chat",body);}}
 private String read(InputStream in)throws Exception{if(in==null)return "{}";try(Reader r=new InputStreamReader(in,StandardCharsets.UTF_8)){StringBuilder b=new StringBuilder();char[] buf=new char[4096];int n;while((n=r.read(buf))!=-1){if(b.length()+n>1000000)throw new IOException();b.append(buf,0,n);}return b.toString();}}
 private void schedule(){JobScheduler j=(JobScheduler)getSystemService(JOB_SCHEDULER_SERVICE);int ok=j.schedule(new JobInfo.Builder(71717,new ComponentName(this,ReminderService.class)).setPeriodic(3600000).setPersisted(true).build());message(ok==JobScheduler.RESULT_SUCCESS?"تم تفعيل تذكير محلي تقريبي؛ لا يعمل والهاتف مطفأ":"تعذر جدولة التنبيه");}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==NOTIFICATIONS&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)schedule();if(r==VOICE_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startVoiceService();else if(r==VOICE_PERMISSION){message("يحتاج وضع المحادثة الصوتية إلى إذن الميكروفون");js("voiceSessionChanged","false");}}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null){if(r==JOB_EXPORT)prefs.edit().remove("job_export_name").remove("job_export_content").apply();return;}if((r==EXPORT||r==PROFILE||r==JOB_EXPORT)&&d.getData()!=null){try(OutputStream out=getContentResolver().openOutputStream(d.getData())){if(out==null)throw new IOException();if(r==EXPORT){out.write(prefs.getString("state","{}").getBytes(StandardCharsets.UTF_8));message("حُفظت النسخة الاحتياطية في المكان الذي اخترته");}else if(r==JOB_EXPORT){out.write(prefs.getString("job_export_content","").getBytes(StandardCharsets.UTF_8));prefs.edit().remove("job_export_name").remove("job_export_content").apply();message("حُفظ مخرج العمل في المكان الذي اخترته");}else{try(InputStream in=getAssets().open("enjaz-profile-ar.pdf")){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);}message("حُفظ ملف الخبرة PDF في المكان الذي اخترته");}}catch(Exception e){if(r==JOB_EXPORT)prefs.edit().remove("job_export_name").remove("job_export_content").apply();message(r==EXPORT?"تعذر حفظ النسخة الاحتياطية":r==JOB_EXPORT?"تعذر تصدير مخرج العمل":"تعذر تصدير ملف الخبرة");}}}
 @Override public void onBackPressed(){if(web==null){super.onBackPressed();return;}web.evaluateJavascript("window.ramBack ? window.ramBack() : false",value->{if(!"true".equals(value))MainActivity.super.onBackPressed();});}
 private boolean voiceSessionActive(){return getSharedPreferences("ram_voice",MODE_PRIVATE).getBoolean("active",false);}
 private void startVoiceService(){try{Intent i=new Intent(this,VoiceConversationService.class);i.setAction(VoiceConversationService.ACTION_START);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);getSharedPreferences("ram_voice",MODE_PRIVATE).edit().putBoolean("active",true).apply();js("voiceSessionChanged","true");}catch(Exception e){message("تعذر تشغيل المحادثة الصوتية. افتح رام واضغط بدء المحادثة من جديد.");}}
 private void resumeVoiceRecognition(){if(dead||!voiceSessionActive())return;try{Intent i=new Intent(this,VoiceConversationService.class);i.setAction(VoiceConversationService.ACTION_RESUME);startService(i);}catch(Exception ignored){}}
 private String postVoiceWav(byte[] audio)throws Exception{HttpURLConnection c=null;try{String server=serverBaseUrl();c=(HttpURLConnection)new URL(server+"/voice/transcribe").openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(20000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","audio/wav");String token=prefs.getString("connection_token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);c.setDoOutput(true);try(OutputStream out=c.getOutputStream()){out.write(audio);}int status=c.getResponseCode();String raw=read(status>=200&&status<300?c.getInputStream():c.getErrorStream());if(status<200||status>=300){String reason="تعذر تحويل الصوت ("+status+")";try{String serverError=new JSONObject(raw).optString("error","");if(!serverError.isEmpty())reason=serverError;}catch(Exception ignored){}throw new IOException(reason);}return raw;}finally{if(c!=null)c.disconnect();}}
 private void transcribeVoiceFile(String path){new Thread(()->{File clip=null;try{File dir=new File(getCacheDir(),"ram-voice").getCanonicalFile();clip=new File(path).getCanonicalFile();if(!clip.getPath().startsWith(dir.getPath()+File.separator)||!clip.isFile()||clip.length()<44||clip.length()>6_000_000)throw new IOException("مقطع الصوت غير صالح أو تجاوز الحد المسموح.");byte[] data;try(FileInputStream in=new FileInputStream(clip);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(out.size()+n>6_000_000)throw new IOException("مقطع الصوت أطول من الحد المسموح.");out.write(buf,0,n);}data=out.toByteArray();}JSONObject result=new JSONObject(postVoiceWav(data));String text=result.optString("text","").trim();if(text.isEmpty())throw new IOException("لم ألتقط كلامًا واضحًا. تحدث بعد سماع حالة الاستماع.");js("voiceText",JSONObject.quote(text));}catch(Exception e){String why=e.getMessage()==null?"تعذر إرسال الصوت إلى رام.":e.getMessage();if(e instanceof UnknownHostException||why.contains("Unable to resolve host"))why="عنوان خادم رام لا يُحل حاليًا. حدّث Public Domain من إعدادات Railway ثم ضعه في إعدادات رام.";js("voiceError",JSONObject.quote(why));resumeVoiceRecognition();}finally{if(clip!=null)clip.delete();}} ,"ram-voice-transcribe").start();}
 private void registerVoiceReceiver(){voiceReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(i==null)return;String action=i.getAction();if(VoiceConversationService.ACTION_AUDIO_READY.equals(action)){transcribeVoiceFile(i.getStringExtra("path"));}else if(VoiceConversationService.ACTION_LISTENING.equals(action)){js("voiceListening","null");}else if(VoiceConversationService.ACTION_PROCESSING.equals(action)){js("voiceProcessing","null");}else if(VoiceConversationService.ACTION_ERROR.equals(action)){String error=i.getStringExtra("message");js("voiceError",JSONObject.quote(error==null||error.isEmpty()?"تعذر استخدام الميكروفون.":error));}else if(VoiceConversationService.ACTION_STOPPED.equals(action)){getSharedPreferences("ram_voice",MODE_PRIVATE).edit().putBoolean("active",false).apply();js("voiceSessionChanged","false");}}};IntentFilter f=new IntentFilter();f.addAction(VoiceConversationService.ACTION_AUDIO_READY);f.addAction(VoiceConversationService.ACTION_LISTENING);f.addAction(VoiceConversationService.ACTION_PROCESSING);f.addAction(VoiceConversationService.ACTION_ERROR);f.addAction(VoiceConversationService.ACTION_STOPPED);if(Build.VERSION.SDK_INT>=33)registerReceiver(voiceReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(voiceReceiver,f);voiceReceiverRegistered=true;}
 @Override protected void onDestroy(){dead=true;if(voiceReceiverRegistered){try{unregisterReceiver(voiceReceiver);}catch(Exception ignored){}}if(request!=null)request.disconnect();if(ttsRequest!=null)ttsRequest.disconnect();stopCloudPlayback();if(speech!=null){speech.stop();speech.shutdown();}web.removeJavascriptInterface("Android");web.destroy();super.onDestroy();}
}
