const test=require('node:test'),assert=require('node:assert/strict'),C=require('../app/src/main/assets/core.js');
const base=()=>({id:'j',stage:'NEW',amount:10000,currency:'USD',basis:'FIXED',events:[]});
test('cannot skip work stages or infer receipt from an AI response',()=>{assert.throws(()=>C.next(base(),'RECEIVED',{confirmedByOwner:true,amount:'100'}));assert.throws(()=>C.next(base(),'SELECTED',{}));});
test('full workflow requires agreement, proof, due date, payout method and personal receipt confirmation',()=>{let j=C.next(base(),'SELECTED',{approved:true},1);assert.throws(()=>C.next(j,'IN_PROGRESS'));j=C.next(j,'IN_PROGRESS',{agreement:'Scope accepted'},2);assert.equal(j.agreement,'Scope accepted');assert.throws(()=>C.next(j,'DELIVERED'));j=C.next(j,'DELIVERED',{proof:'Email 123'},3);assert.throws(()=>C.next(j,'PAYMENT_PENDING',{dueAt:10}));j=C.next(j,'PAYMENT_PENDING',{dueAt:10,payoutMethod:'MONEYGRAM'},4);assert.equal(j.payoutMethod,'MONEYGRAM');assert.equal(C.overdue(j,86400009),false);assert.equal(C.overdue(j,86400010),true);j=C.next(j,'PAYMENT_REPORTED',{reference:'Transfer notice'},5);assert.throws(()=>C.next(j,'RECEIVED',{amount:'100',method:'BANK'}));j=C.next(j,'RECEIVED',{confirmedByOwner:true,amount:'100',currency:'USD',method:'BANK'},6);assert.equal(j.receipt.amount,10000);assert.equal(C.legalQueue([j],999999999).length,0);assert.equal(j.events.length,6);});
test('money is exact, unknown is not zero and currencies are not combined',()=>{assert.equal(C.cents('10.01'),1001);assert.equal(C.cents(''),null);assert.throws(()=>C.cents('-5'));assert.throws(()=>C.cents('1.111'));const a={...base(),stage:'PAYMENT_PENDING'},b={...a,currency:'EUR'};assert.deepEqual(C.totals([a,b],false),{'USD / FIXED':10000,'EUR / FIXED':10000});assert.equal(C.sorted([{...a,amount:null},a],'USD','FIXED')[0].amount,10000);});
test('unsafe source links are rejected',()=>{assert.equal(C.url('javascript:alert(1)'),false);assert.equal(C.url('https://example.com/job'),true);});
test('payment claim is prepared from delivered work and never treated as sent or received',()=>{const draft=C.paymentClaim({title:'ترجمة صفحة',agreedAmount:2500,currency:'USD',payoutMethod:'MONEYGRAM',deliveryProof:'https://example.com/delivery'},{recipient:'Ahmed Abdulkarim Ahmed Oshish',phone:'+96771377288'});assert.match(draft.subject,/ترجمة صفحة/);assert.match(draft.body,/25\.00 USD/);assert.match(draft.body,/MoneyGram/);assert.match(draft.body,/https:\/\/example\.com\/delivery/);assert.match(draft.body,/Ahmed Abdulkarim Ahmed Oshish/);assert.match(draft.body,/ليست إثباتًا لاستلام المال/);assert.doesNotMatch(draft.body,/تم إرسال المطالبة/);});
test('USDT claim omits wallet until address and network are both saved',()=>{const job={title:'تنسيق شحنة',currency:'USD',payoutMethod:'USDT'};const pending=C.paymentClaim(job,{});assert.match(pending.body,/سأرسل عنوان المحفظة والشبكة/);const ready=C.paymentClaim(job,{usdtWalletAddress:'T12345678901234567890123456789012',usdtNetwork:'TRC20'});assert.match(ready.body,/TRC20/);assert.match(ready.body,/T12345678901234567890123456789012/);});
test('final payment amount and currency override an advertised estimate',()=>{const j={...base(),stage:'DELIVERED',amount:10000,currency:'USD',deliveryProof:'receipt link'};const paid=C.next(j,'PAYMENT_PENDING',{claimAmountCents:7350,claimCurrency:'EUR',dueAt:50,payoutMethod:'BANK'},5);assert.equal(paid.amount,7350);assert.equal(paid.agreedAmount,7350);assert.equal(paid.currency,'EUR');});
