'use strict';
const C=RamCore,$=id=>document.getElementById(id),tabs={home:'لوحة رام',chat:'المحادثة',opportunities:'الفرص',daily:'اختياري اليومي',active:'الأعمال الجارية',delivered:'الأعمال المنجزة',dues:'المستحقات المالية',contacts:'الشركات والموردون',legal:'المتابعة القانونية',portfolio:'الأعمال المكتملة',settings:'الإعدادات والربط'};
let state={version:1,jobs:[],contacts:[],messages:[],settings:{}},tab='home',busy=false,results=[],serverCapabilities=null,searchCategory='';
try{const saved=JSON.parse(Android.load());if(saved&&saved.version===1)state=saved;}catch(e){}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4500);}
function save(fn){const copy=JSON.parse(JSON.stringify(state));fn(copy);if(!Android.save(JSON.stringify(copy)))throw Error('تعذر الحفظ على الهاتف؛ لم تُعتمد العملية');state=copy;}
function act(fn){try{fn();}catch(e){toast(e.message);}}
function button(t,fn,cls){const b=el('button',t,cls);b.onclick=()=>act(fn);return b;}
function card(parent,title){const d=el('section',undefined,'card');if(title)d.append(el('h3',title));parent.append(d);return d;}
function link(parent,url,title='فتح المصدر'){if(C.url(url))parent.append(button(title,()=>Android.openUrl(url)));}
function field(form,name,label,type='text',value=''){const l=el('label',label,'field');let i;if(Array.isArray(type)){i=el('select');for(const [val,title] of type){const o=el('option',title);o.value=val;i.append(o);}}else{i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;if(type==='number'){i.step='0.01';i.min='0.01';}}i.name=name;if(!Array.isArray(type)||value!==''&&value!=null)i.value=value??'';l.append(i);form.append(l);return i;}
const categories=[['TRANSLATION','الترجمة'],['ENGINEERING','الهندسة والديكور والتصميم'],['TECH','المواقع والبرمجة'],['RESEARCH','الأبحاث وتطوير المشاريع'],['LOGISTICS','الشحن'],['ENERGY','النفط والغاز'],['SOURCING','التوريد'],['PROPERTY','العقارات والسياحة']];
const currencies=[['USD','USD'],['EUR','EUR'],['GBP','GBP'],['AED','AED'],['SAR','SAR'],['YER','YER'],['USDT','USDT']];const basis=[['FIXED','مبلغ للمشروع'],['HOURLY','للساعة'],['COMMISSION','عمولة معلنة']];
function money(j){return j.amount==null?'المبلغ غير معلن':(j.amount/100).toLocaleString('ar',{maximumFractionDigits:2})+' '+j.currency+' · '+(basis.find(x=>x[0]===j.basis)?.[1]||'');}
function dialog(title,build){const m=$('modal');m.replaceChildren(el('h2',title));build(m);m.append(button('إغلاق',()=>m.close()));m.showModal();}
function formDialog(title,fields,onSubmit){dialog(title,m=>{const f=el('form');m.append(f);fields.forEach(x=>field(f,...x));f.append(button('حفظ وتأكيد',()=>{},'primary'));f.onsubmit=e=>{e.preventDefault();act(()=>{onSubmit(Object.fromEntries(new FormData(f)));m.close();render();});};});}
const primaryTabs=['home','opportunities','active','dues','settings'];
function go(k){tab=k;render();}
function render(){const n=$('nav');n.replaceChildren();n.className='main-nav';for(const k of primaryTabs)n.append(button(tabs[k],()=>go(k),tab===k?'active':''));const main=$('main');main.replaceChildren();main.append(el('h2',tabs[tab]));
 if(tab==='home')return dashboard(main);if(tab==='chat')return chat(main);if(tab==='opportunities')return opportunities(main);if(tab==='settings')return settings(main);if(tab==='contacts')return contacts(main);
 if(tab==='dues'){const grid=el('div',undefined,'grid');main.append(grid);for(const [key,val]of Object.entries(C.totals(state.jobs,false))){const d=el('div',undefined,'stat');d.append(el('small',key),el('b',(val/100).toLocaleString('ar')));grid.append(d);}main.append(el('p','المتوقع ليس محصلًا. لا تُجمع العملات أو المبالغ بالساعة مع المبالغ الثابتة.','muted'));}
 const jobs=state.jobs.filter(j=>tab==='daily'?j.stage==='SELECTED':tab==='active'?['SELECTED','IN_PROGRESS'].includes(j.stage):tab==='delivered'?['DELIVERED','PAYMENT_PENDING','PAYMENT_REPORTED'].includes(j.stage):tab==='dues'?['PAYMENT_PENDING','PAYMENT_REPORTED'].includes(j.stage):tab==='portfolio'?j.stage==='RECEIVED':false);
 if(tab==='legal'){main.append(el('p','تدخل هنا المستحقات المتأخرة 24 ساعة بعد تاريخ الاستحقاق المتفق عليه، أو الملفات التي فتحتها للمراجعة. لا يُرسل بلاغ أو يُبدأ تحكيم تلقائيًا، ولا يُصنف العميل محتالًا بمجرد التأخر.','muted'));C.legalQueue(state.jobs).forEach(j=>jobCard(main,j));if(!C.legalQueue(state.jobs).length)main.append(el('p','لا توجد ملفات تحتاج مراجعة حاليًا.','empty'));return;}
 if(!jobs.length)main.append(el('p','لا توجد أعمال مسجلة في هذه المرحلة.','empty'));jobs.forEach(j=>jobCard(main,j));
}
function dashboard(main){
 const active=state.jobs.filter(j=>['SELECTED','IN_PROGRESS','DELIVERED','PAYMENT_PENDING','PAYMENT_REPORTED'].includes(j.stage)).length;
 const completed=state.jobs.filter(j=>j.stage==='RECEIVED').length;
 const pending=state.jobs.filter(j=>['PAYMENT_PENDING','PAYMENT_REPORTED'].includes(j.stage)).length;
 const grid=el('div',undefined,'grid');main.append(grid);
 for(const [title,count,key] of [['أعمال قيد المتابعة',active,'active'],['أعمال مكتملة باستلامك',completed,'portfolio'],['مستحقات تنتظر المتابعة',pending,'dues'],['فرص جديدة محفوظة',state.jobs.filter(j=>j.stage==='NEW').length,'opportunities']]){const d=button('',()=>go(key),'stat tile');d.append(el('small',title),el('b',String(count)));grid.append(d);}
 const welcome=card(main,'ابدأ من هنا');welcome.append(el('p','ابحث عن فرصة من مصدرها، راجع شروطها ومبلغها، ثم اختر أنت ما يدخل قائمة عمل رام. الاختيار لا يسجل حسابًا ولا يرسل عرضًا للعميل.','muted'));
 welcome.append(button('بحث وفرص حسب المجال',()=>go('opportunities'),'primary'),button('افتح المحادثة',()=>go('chat')));
 const more=card(main,'الأقسام الأخرى');const shortcuts=el('div',undefined,'grid');more.append(shortcuts);
 for(const k of ['chat','daily','delivered','contacts','legal','portfolio']){const b=button(tabs[k],()=>go(k));shortcuts.append(b);}
 const status=card(main,'الاتصال والخصوصية');status.append(el('p','سجل الأعمال محلي على الهاتف. حالة المحادثة والبحث تظهر في الإعدادات بعد اختبار اتصال الخادم. لم نربط بريدك أو حساب Google بعد.','muted'),button('فتح الإعدادات والربط',()=>{go('settings');checkCapabilities();}));
}
function checkCapabilities(){serverCapabilities=null;try{Android.checkCapabilities();}catch{}}
window.searchReply=data=>{if(data.error){toast(data.error);return;}results=Array.isArray(data.results)?data.results.filter(x=>C.url(x.url)):[];const answer=String(data.answer||data.reply||'تم جلب النتائج من الويب.');save(s=>s.messages.push({role:'assistant',content:answer}));tab='opportunities';render();};
window.capabilitiesReply=data=>{serverCapabilities=data||null;if(tab==='settings')render();};

function jobCard(parent,j){const d=card(parent,j.title);d.append(el('span',C.labels[j.stage],'badge'),el('p',money(j),'money'));d.append(el('p',j.client||'الجهة تحتاج تحقق'),el('p',j.details));if(j.deadline)d.append(el('p','موعد التسليم المتفق: '+j.deadline));if(j.dueAt)d.append(el('p','الاستحقاق: '+new Date(j.dueAt).toLocaleString('ar')));if(C.overdue(j))d.append(el('p','تجاوز موعد الاستحقاق بأكثر من 24 ساعة؛ راجع الاتفاق وأسباب التأخير.','warn'));const row=el('div',undefined,'row');d.append(row);link(row,j.source);row.append(button('التفاصيل والسجل',()=>details(j)));
 const next=C.stages[C.stages.indexOf(j.stage)+1];if(next)row.append(button(({SELECTED:'اختيار هذه الفرصة',IN_PROGRESS:'تسجيل بدء التنفيذ',DELIVERED:'تسجيل التسليم',PAYMENT_PENDING:'متابعة المستحق',PAYMENT_REPORTED:'سجل إشعار التحويل',RECEIVED:'أؤكد أنني استلمت المبلغ'})[next],()=>advance(j,next),'primary'));
 if(j.stage!=='RECEIVED')row.append(button('سجل متابعة',()=>formDialog('متابعة العمل',[['note','نتيجة المراسلة أو الخطوة التالية','textarea'],['followUpAt','موعد المتابعة القادم','datetime-local']],v=>{if(!v.note.trim())throw Error('اكتب تفاصيل المتابعة');save(s=>{const a=s.jobs.find(x=>x.id===j.id);a.events.push({at:Date.now(),note:v.note,actor:'OWNER'});a.followUpAt=v.followUpAt?new Date(v.followUpAt).getTime():null;});})));
 if(j.stage==='RECEIVED')d.append(el('p','استلام مؤكد منك: '+(j.receipt.amount/100)+' '+j.receipt.currency+' · '+new Date(j.receipt.confirmedAt).toLocaleString('ar')));
}
function details(j){dialog(j.title,m=>{m.append(el('p',j.details),el('p','المصدر: '+j.source),el('p','سجل محلي. تغيير المرحلة لا يرسل العمل أو الأموال تلقائيًا.','muted'));for(const e of j.events){const d=el('div',undefined,'event');d.append(el('small',new Date(e.at).toLocaleString('ar')),el('p',(C.labels[e.stage]||'متابعة')+' — '+e.note));m.append(d);}m.append(button('فتح ملف للمراجعة القانونية',()=>{save(s=>{let a=s.jobs.find(x=>x.id===j.id);a.legalOpen=true;a.events.push({at:Date.now(),note:'فتح ملف مراجعة دون إرسال بلاغ',actor:'OWNER'});});m.close();tab='legal';render();}),button('تجهيز رسالة متابعة',()=>{m.close();tab='chat';render();$('message').value='جهز مسودة متابعة مهنية دون اتهامات أو ادعاء إرسالها لهذا العمل: '+j.title+'، الحالة: '+C.labels[j.stage]+'، المبلغ: '+money(j)+'، المصدر: '+j.source; }));});}
function advance(j,to){let fields=[];if(to==='SELECTED'){dialog('تأكيد اختيار الفرصة',m=>{m.append(el('p','اختيارك يحفظ الفرصة في قائمتك اليومية. لا يعني قبول العميل أو توقيع عقد أو إرسال عرض.'));m.append(button('أوافق على اختيارها',()=>{save(s=>{s.jobs=s.jobs.map(x=>x.id===j.id?C.next(x,to,{approved:true}):x);});m.close();render();},'primary'));});return;}
 if(to==='IN_PROGRESS')fields=[['agreement','الاتفاق المقبول ونطاق العمل والمخرجات','textarea']];
 if(to==='DELIVERED')fields=[['proof','رابط المخرجات أو مرجع رسالة التسليم الفعلي','textarea']];
 if(to==='PAYMENT_PENDING')fields=[['dueAt','موعد استحقاق الدفع حسب الاتفاق','datetime-local']];
 if(to==='PAYMENT_REPORTED')fields=[['reference','مرجع إشعار التحويل ومن أرسله','textarea']];
 if(to==='RECEIVED')fields=[['amount','المبلغ الذي تحققت من وصوله فعليًا','number',j.amount==null?'':j.amount/100],['currency','عملة الاستلام',currencies,j.currency],['method','وسيلة الاستلام',[['BANK','حوالة بنكية'],['WESTERN_UNION','Western Union'],['MONEYGRAM','MoneyGram'],['USDT','USDT']]],['reference','مرجع الاستلام بعد التحقق','text'],['confirm','اكتب استلمت لتأكيد وصول المبلغ','text']];
 formDialog(to==='RECEIVED'?'تأكيد شخصي لاستلام المال':C.labels[to],fields,v=>{if(to==='RECEIVED'&&v.confirm.trim()!=='استلمت')throw Error('اكتب استلمت بعد التحقق من وصول المال');if(v.dueAt)v.dueAt=new Date(v.dueAt).getTime();if(to==='RECEIVED')v.confirmedByOwner=true;save(s=>s.jobs=s.jobs.map(x=>x.id===j.id?C.next(x,to,v):x));});}
function resultCard(parent,r,i){const d=card(parent,`${i+1}. ${r.title||'نتيجة بحث'}`);const text=(r.title||'')+' '+(r.snippet||'');const fee=/upfront fee|application fee|pay to apply|registration fee|deposit required|رسوم تقديم|رسوم اشتراك|ادفع للتسجيل|مبلغ مقدم/i.test(text);const price=Number.isSafeInteger(r.amountCents)?`المبلغ المعلن: ${(r.amountCents/100).toLocaleString('ar')} ${r.currency||''} · ${r.basis==='HOURLY'?'للساعة':''} — يحتاج تحققًا`:'المبلغ غير واضح في الإعلان المتاح؛ لم نخمن السعر.';d.append(el('p',r.snippet||'لا يوجد وصف متاح.'),el('p',price,'money'),r.amountEvidence?el('small','موضع المبلغ في المصدر: '+r.amountEvidence):el('span',''),el('p',fee?'تحذير: يبدو أن المصدر يذكر رسومًا أو دفعة مقدمة؛ لا تسجّل أو تدفع قبل التحقق.':'تحقق من شروط التسجيل والرسوم؛ لا يشترك رام ولا يدفع نيابةً عنك.','muted'));link(d,r.url,'فتح إعلان الفرصة');d.append(button('مراجعة وحفظ الفرصة',()=>addOpportunity(r),'primary'));}
function opportunities(main){const row=el('div',undefined,'row');main.append(row);row.append(button('بحث عن فرص',()=>{tab='chat';render();$('message').value='ابحث عن فرص مشاريع مدفوعة منشورة مع المصدر والميزانية والعملة والأجل لكل فرصة. لا تخترع مبلغًا غير معلن.';}),button('حفظ فرصة من مصدر',()=>addOpportunity()));main.append(el('p','تصفّح الفرص حسب المجال. يعرض RAM مصدر الإعلان والمبلغ المعلن فقط؛ لا يخترع دخلًا ولا يشترك أو يرسل عرضًا. اعمل على المواقع المجانية فقط وتحقق من شروط كل فرصة.','muted'));const search=el('form',undefined,'row');const category=field(search,'searchCategory','مجال البحث',[['','كل المجالات'],...categories]);const query=el('input');query.placeholder='مثال: ترجمة عربية إنجليزية مدفوعة دون رسوم تقديم';query.maxLength=2000;query.required=true;search.append(query);const searchBtn=el('button','ابحث في الويب','primary');search.append(searchBtn);main.append(search);if(results.length){const ordered=results.slice().sort((a,b)=>{const ac=Number.isSafeInteger(a.amountCents)?a.amountCents:-1,bc=Number.isSafeInteger(b.amountCents)?b.amountCents:-1;if(a.currency!==b.currency)return String(a.currency||'ZZZ').localeCompare(String(b.currency||'ZZZ'));return bc-ac;});main.append(el('h3',`نتائج حقيقية من الويب (${ordered.length}) · المبالغ المفصح عنها أولًا ضمن العملة نفسها`));for(const [i,r] of ordered.entries())resultCard(main,r,i);}search.onsubmit=e=>{e.preventDefault();const q=query.value.trim();if(!q)return;const selected=categories.find(x=>x[0]===category.value)?.[1]||'مشاريع عن بعد متنوعة';Android.search(`${selected}: ${q}. أعمال حقيقية منشورة، دون رسوم تقديم أو دفعة مسبقة؛ أظهر رابط المصدر والمبلغ المعلن والعملة وموعد العمل إن وجدت. لا تخترع معلومات.`);toast('جارٍ البحث في المصادر المتاحة…');};const filters=el('div',undefined,'row');main.append(filters);const cat=field(filters,'cat','المجال',[['','كل المجالات'],...categories]),cur=field(filters,'currency','العملة',[['','كل العملات منفصلة'],...currencies]),bas=field(filters,'basis','السعر',[['','كل الأنواع منفصلة'],...basis]);const list=el('div');main.append(list);function show(){list.replaceChildren();const jobs=C.sorted(state.jobs.filter(j=>j.stage==='NEW'&&(!cat.value||cat.value===j.category)),cur.value,bas.value);jobs.forEach(j=>jobCard(list,j));if(!jobs.length)list.append(el('p','لا توجد فرص محفوظة. لن نملأ هذه القائمة بفرص تجريبية أو مبالغ وهمية.','empty'));}cat.onchange=cur.onchange=bas.onchange=show;show();}
function addOpportunity(seed={}){formDialog('حفظ فرصة ومصدرها',[['title','عنوان العمل','text',seed.title],['category','القسم',categories,seed.category],['source','رابط الإعلان الأصلي','url',seed.url],['client','اسم العميل أو الشركة','text'],['details','المتطلبات والمخرجات والشروط','textarea',seed.snippet],['amount','المبلغ المعلن أو المتفق عليه فقط؛ اتركه فارغًا إن لم يُذكر','number',Number.isSafeInteger(seed.amountCents)?seed.amountCents/100:''],['currency','العملة',currencies,seed.currency],['basis','نوع السعر',basis,seed.basis||'FIXED'],['deadline','موعد التسليم المعلن أو المتفق عليه','date']],v=>{if(!v.title.trim()||!v.details.trim()||!C.url(v.source))throw Error('أدخل العنوان والتفاصيل ورابط مصدر صالح');if(state.jobs.some(x=>x.source===v.source&&x.title===v.title))throw Error('هذه الفرصة محفوظة بالفعل');save(s=>s.jobs.push({...v,id:Android.newId(),stage:'NEW',amount:C.cents(v.amount),createdAt:Date.now(),events:[{at:Date.now(),stage:'NEW',note:'أدخلها المستخدم من المصدر؛ ليست عقدًا مؤكدًا',actor:'OWNER'}]}));});}
function contacts(main){main.append(el('p','سجل جهات العمل يدويًا من مصادر عامة موثقة. لا يقرأ دفتر عناوينك أو صورك الخاصة.','muted'),button('إضافة شركة أو جهة',()=>formDialog('بيانات جهة موثقة',[['name','الاسم','text'],['kind','الصفة',[['COMPANY','شركة'],['SUPPLIER','مورد'],['IMPORTER','مستورد أو مشترٍ'],['CLIENT','عميل'],['CARRIER','شركة شحن']]],['source','رابط المصدر العام','url'],['email','بريد التواصل المعلن','email'],['phone','هاتف العمل المعلن','tel'],['notes','الخدمات والبلد وملاحظات التحقق','textarea']],v=>{if(!v.name.trim()||!C.url(v.source))throw Error('الاسم ومصدر البيانات مطلوبان');save(s=>s.contacts.push({...v,id:Android.newId(),createdAt:Date.now()}));})));if(!state.contacts.length)main.append(el('p','لا توجد جهات محفوظة. لا تُستورد صورك أو جهات اتصالك الشخصية هنا.','empty'));for(const c of state.contacts){const d=card(main,c.name);d.append(el('p',c.email+' '+c.phone),el('p',c.notes));link(d,c.source);}}
function chat(main){main.append(el('p','المحادثة تحتاج اتصالًا بالخادم. لا توجد صلاحيات إرسال بريد أو تنفيذ مكالمات أو دفع أو سحب في هذه النسخة.','muted'));const chat=el('div');main.append(chat);for(const x of state.messages){const d=card(chat,x.role==='user'?'أنت':'RAM');d.classList.toggle('user',x.role==='user');d.append(el('p',x.content,'chat'));}if(results.length){chat.append(el('h3','نتائج بحث من المصدر · راجعها قبل الاختيار'));for(const [i,r] of results.entries())resultCard(chat,r,i);}
 const form=el('form',undefined,'composer'),input=el('textarea');input.id='message';input.placeholder='اكتب طلبك إلى رام…';input.maxLength=6000;form.append(input);const send=el('button',busy?'جارٍ الرد…':'أرسل','primary');send.disabled=busy;form.append(send);main.append(form);form.onsubmit=e=>{e.preventDefault();act(()=>{const message=input.value.trim();if(!message||busy)return;const history=state.messages.slice(-20);save(s=>s.messages.push({role:'user',content:message}));busy=true;results=[];Android.chat(JSON.stringify({message,history}));render();});};$('orb').classList.toggle('thinking',busy);
 const row=el('div',undefined,'row');row.append(button('تحدث',()=>Android.dictate()),button('إيقاف الصوت',()=>Android.stopVoice()));main.append(row);}
window.voiceText=t=>{tab='chat';render();$('message').value=t;};
window.reply=data=>{busy=false;act(()=>{if(data.error){toast(data.error);save(s=>s.messages.push({role:'assistant',content:'لم يكتمل الطلب: '+data.error}));}else{const content=String(data.response||data.reply||'');if(/^\s*(?:(?:user|content)\s+safety\s*:\s*)?(?:safe|unsafe)\s*[.!]?\s*$/i.test(content)){toast('الخادم أعاد نتيجة تصنيف بدل محادثة. يجب مراجعة النموذج.');return;}save(s=>{s.messages.push({role:'assistant',content});s.messages=s.messages.slice(-80);});results=Array.isArray(data.results)?data.results.filter(x=>C.url(x.url)):[];if(state.settings.voiceEnabled){if(state.settings.voiceProvider==='elevenlabs')Android.speakCloud(content);else Android.speak(content);}}});render();};
function settings(main){let voices=[];try{voices=JSON.parse(Android.getVoices()||'[]').map(v=>[v.name,`${v.locale} · ${v.name}`]);}catch{}const d=card(main,'حالة الخدمات الفعلية');const online=serverCapabilities;d.append(el('p',online&&!online.error?`الخادم يرد · المحادثة ${online.chatConfigured?'جاهزة للإعداد':'تحتاج مفتاح مزود'} · البحث ${online.searchConfigured?'متصل':'غير متصل'} · ElevenLabs ${online.elevenLabsConfigured?'مفتاح محفوظ':'غير مهيأ'} / ${online.elevenLabsEnabled?'مفعّل':'موقوف'} · البريد ${online.emailConnected?'متصل':'غير متصل'} · مهام السحابة ${online.cloudJobsConnected?'متصلة':'غير متصلة'}`:online?.error?'تعذر التحقق: '+online.error:'اختبر الاتصال لتحديث الحالة. لا تظهر الخدمة على أنها متصلة قبل نجاح الرد.','muted'));d.append(button('اختبار الخادم والبحث',()=>checkCapabilities()));
 const f=el('form');main.append(f);field(f,'server','عنوان خادم HTTPS','url',state.settings.server||'https://ram-agent-production.up.railway.app');field(f,'connectionToken','رمز اتصال رام الخاص — اتركه فارغًا للاحتفاظ بالمحفوظ','password','');field(f,'recipient','اسم مستلم الحوالة كما في الهوية','text',state.settings.recipient||'');field(f,'phone','هاتف التواصل','tel',state.settings.phone||'');field(f,'voiceProvider','محرك الصوت',[['device','صوت الهاتف · مجاني'],['elevenlabs','ElevenLabs · يستهلك رصيد الحساب']],state.settings.voiceProvider||'device');field(f,'ttsVoice','الصوت العربي المتاح على الجهاز',[['','الصوت الافتراضي'],...voices],state.settings.ttsVoice||'');field(f,'voiceOutput','قراءة الردود',[['no','متوقفة'],['yes','تعمل']],state.settings.voiceEnabled?'yes':'no');field(f,'voicePitch','درجة الصوت',[['low','أخفض'],['normal','عادية'],['high','أعلى']],state.settings.voicePitch||'normal');f.append(el('p','صوت الهاتف مجاني ويظل الاختيار الافتراضي. ElevenLabs يستخدم رصيد حسابك عند قراءة الردود، وحد الخادم 1200 حرف لكل طلب. لا تختره إلا إذا أردت استخدام رصيدك.','muted'));f.append(button('حفظ الإعدادات',()=>{},'primary'));f.onsubmit=e=>{e.preventDefault();act(()=>{const v=Object.fromEntries(new FormData(f));if(!v.server.startsWith('https://')||!C.url(v.server)||new URL(v.server).search||new URL(v.server).hash)throw Error('أدخل رابط HTTPS صالحًا');const token=v.connectionToken;delete v.connectionToken;if(token&&!Android.setConnectionToken(token))throw Error('رمز الاتصال يجب أن يكون 24 حرفًا على الأقل');save(s=>s.settings={...s.settings,...v,voiceEnabled:v.voiceOutput==='yes',voicePitch:v.voicePitch,ttsVoice:v.ttsVoice});if(v.voiceProvider==='elevenlabs'&&v.voiceOutput==='yes'&&serverCapabilities?.elevenLabsEnabled!==true)toast('صوت ElevenLabs يحتاج تفعيل ALLOW_PAID_TTS في Railway؛ سيبقى صوت الهاتف متاحًا.');if(v.ttsVoice&&!Android.setVoice(v.ttsVoice))throw Error('هذا الصوت غير مثبت أو غير متاح بالعربية');Android.setVoicePitch(v.voicePitch);Android.setServer(v.server);toast('تم الحفظ');});};
 const integrations=card(main,'الحسابات والأدوات');integrations.append(el('p','حالة الربط تعرض الواقع فقط. كل بند غير متصل يحتاج إعداد OAuth أو مفتاحًا محفوظًا في الخادم؛ لا تضع كلمات مرورك أو مفاتيح المزودين في التطبيق.','muted'));for(const label of ['بحث الويب العالمي','Google وGmail','إرسال ومتابعة البريد','تخزين سحابي وقاعدة بيانات','تسليم ملفات الترجمة والتصميم','المكالمات الواردة والصادرة','تحكيم وتسوية النزاعات','أدوات المطورين والإنتاجية والشركات','البيانات والتحليلات والبحث العلمي','المالية والاستثمار والعملات الرقمية','السفر والتعليم والصحة والترفيه'])integrations.append(el('p','○ '+label+' — غير متصل حتى إتمام الربط والاختبار','muted'));const about=card(main,'معلومات التطبيق');about.append(el('p','RAM الأعمال · الإصدار 1.9 · إنجاز القابضة · بيانات الأعمال محفوظة محليًا على هذا الهاتف.','muted'),el('p','العمل في الخلفية السحابية، البريد، الحسابات، الاتصالات، إنشاء الحسابات بمواقع العمل، وتسليم الملفات لم تُفعّل بعد. لا تنفذ RAM تحويلًا أو دفعًا أو سحبًا ماليًا.','muted'));
 main.append(button('تفعيل تنبيه محلي كل ساعة تقريبًا',()=>Android.enableReminders()),button('تصدير نسخة احتياطية من سجل العمل',()=>Android.exportData()));main.append(el('p','لا تدخل مفاتيح المحافظ أو كلمات مرور حساباتك. لا تُستخدم بيانات الحوالة لإرسال الأموال. عنوان USDT والشبكة يُتحقق منهما عند الاتفاق.','muted'));}
render();setInterval(()=>{if(['dues','legal','active','home'].includes(tab))render();},60000);
